using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using SkillTree;
using UnityEditor;
using UnityEngine;

public class ModifierCreatorWindow : EditorWindow
{
    private const string DefaultModifiersFolder = "Assets/Scripts/SkillTree/Modifiers/BaseModifiers";

    private readonly List<Type> _modifierTypes = new List<Type>();
    private readonly List<Modifier> _existingModifiers = new List<Modifier>();

    private string[] _modifierTypeNames = Array.Empty<string>();
    private int _selectedTypeIndex;
    private string _assetName = "NewModifier";
    private bool _useAutoGeneratedName = true;
    private DefaultAsset _targetFolder;
    private Vector2 _scroll;

    private Modifier _templateInstance;
    private UnityEditor.Editor _templateEditor;

    [MenuItem("Tools/Modifier Creator")]
    public static void OpenWindow()
    {
        var window = GetWindow<ModifierCreatorWindow>("Modifier Creator");
        window.minSize = new Vector2(420f, 520f);
    }

    private void OnEnable()
    {
        RefreshModifierTypes();

        if (_targetFolder == null)
        {
            _targetFolder = AssetDatabase.LoadAssetAtPath<DefaultAsset>(DefaultModifiersFolder);
        }

        CreateTemplateForSelectedType();
    }

    private void OnDisable()
    {
        DestroyTemplateEditor();
        DestroyTemplateInstance();
    }

    private void OnGUI()
    {
        DrawToolbar();

        if (_modifierTypes.Count == 0)
        {
            EditorGUILayout.HelpBox("No non-abstract Modifier types found.", MessageType.Warning);
            return;
        }

        EditorGUI.BeginChangeCheck();
        _selectedTypeIndex = EditorGUILayout.Popup("Modifier Type", _selectedTypeIndex, _modifierTypeNames);
        if (EditorGUI.EndChangeCheck())
        {
            CreateTemplateForSelectedType();
            if (!_useAutoGeneratedName)
            {
                _assetName = _modifierTypes[_selectedTypeIndex].Name;
            }
        }

        _useAutoGeneratedName = EditorGUILayout.Toggle("Auto Name", _useAutoGeneratedName);
        if (_useAutoGeneratedName)
        {
            var generatedName = GenerateAssetName(_modifierTypes[_selectedTypeIndex], _templateInstance);
            EditorGUI.BeginDisabledGroup(true);
            EditorGUILayout.TextField("Asset Name", generatedName);
            EditorGUI.EndDisabledGroup();
        }
        else
        {
            _assetName = EditorGUILayout.TextField("Asset Name", _assetName);
        }

        _targetFolder = (DefaultAsset)EditorGUILayout.ObjectField("Target Folder", _targetFolder, typeof(DefaultAsset), false);
        var folderPath = GetFolderPath();
        EditorGUILayout.LabelField("Resolved Path", folderPath);

        var targetAssetPath = GetTargetAssetPath();
        RefreshExistingModifiers(folderPath, targetAssetPath);

        if (_existingModifiers.Count > 0)
        {
            EditorGUILayout.HelpBox($"Found {_existingModifiers.Count} modifier asset(s) with this file name in selected folder and subfolders.", MessageType.Warning);

            for (var i = 0; i < _existingModifiers.Count; i++)
            {
                using (new EditorGUI.DisabledScope(true))
                {
                    EditorGUILayout.ObjectField($"Existing Modifier {i + 1}", _existingModifiers[i], typeof(Modifier), false);
                }
            }
        }

        EditorGUILayout.Space(6f);
        EditorGUILayout.LabelField("Initial Values", EditorStyles.boldLabel);

        if (_templateInstance != null && _templateEditor != null)
        {
            _scroll = EditorGUILayout.BeginScrollView(_scroll);
            _templateEditor.OnInspectorGUI();
            EditorGUILayout.EndScrollView();
        }

        EditorGUILayout.Space(10f);

        using (new EditorGUI.DisabledScope(!CanCreateAsset(folderPath)))
        {
            if (GUILayout.Button("Create Modifier Asset", GUILayout.Height(28f)))
            {
                CreateModifierAsset(folderPath);
            }
        }
    }

    private void DrawToolbar()
    {
        using (new EditorGUILayout.HorizontalScope(EditorStyles.toolbar))
        {
            if (GUILayout.Button("Refresh Types", EditorStyles.toolbarButton, GUILayout.Width(100f)))
            {
                RefreshModifierTypes();
                CreateTemplateForSelectedType();
            }

            GUILayout.FlexibleSpace();
        }
    }

    private void RefreshModifierTypes()
    {
        _modifierTypes.Clear();

        var modifierBaseType = typeof(Modifier);

        var types = AppDomain.CurrentDomain.GetAssemblies()
            .SelectMany(GetLoadableTypes)
            .Where(type =>
                type != null &&
                type.IsClass &&
                !type.IsAbstract &&
                modifierBaseType.IsAssignableFrom(type))
            .OrderBy(type => type == typeof(BaseModifier) ? 0 : 1)
            .ThenBy(type => type.Name)
            .ToList();

        _modifierTypes.AddRange(types);
        _modifierTypeNames = _modifierTypes.Select(type => type.FullName ?? type.Name).ToArray();

        if (_modifierTypes.Count == 0)
        {
            _selectedTypeIndex = 0;
            return;
        }

        _selectedTypeIndex = Mathf.Clamp(_selectedTypeIndex, 0, _modifierTypes.Count - 1);
    }

    private void CreateTemplateForSelectedType()
    {
        DestroyTemplateEditor();
        DestroyTemplateInstance();

        if (_modifierTypes.Count == 0)
        {
            return;
        }

        var selectedType = _modifierTypes[_selectedTypeIndex];
        _templateInstance = ScriptableObject.CreateInstance(selectedType) as Modifier;
        if (_templateInstance == null)
        {
            return;
        }

        _templateInstance.hideFlags = HideFlags.DontSaveInEditor;
        _templateEditor = UnityEditor.Editor.CreateEditor(_templateInstance);

        if (string.IsNullOrWhiteSpace(_assetName) || _assetName == "NewModifier")
        {
            _assetName = selectedType.Name;
        }
    }

    private void DestroyTemplateEditor()
    {
        if (_templateEditor != null)
        {
            DestroyImmediate(_templateEditor);
            _templateEditor = null;
        }
    }

    private void DestroyTemplateInstance()
    {
        if (_templateInstance != null)
        {
            DestroyImmediate(_templateInstance);
            _templateInstance = null;
        }
    }

    private string GetFolderPath()
    {
        if (_targetFolder == null)
        {
            return "Assets";
        }

        var path = AssetDatabase.GetAssetPath(_targetFolder);
        if (string.IsNullOrWhiteSpace(path) || !AssetDatabase.IsValidFolder(path))
        {
            return "Assets";
        }

        return path;
    }

    private bool CanCreateAsset(string folderPath)
    {
        if (_templateInstance == null)
        {
            return false;
        }

        if (!_useAutoGeneratedName && string.IsNullOrWhiteSpace(_assetName))
        {
            return false;
        }

        if (!AssetDatabase.IsValidFolder(folderPath))
        {
            return false;
        }

        return _existingModifiers.Count == 0;
    }

    private string GetTargetAssetPath()
    {
        if (_modifierTypes.Count == 0)
        {
            return string.Empty;
        }

        var selectedType = _modifierTypes[_selectedTypeIndex];

        var rawName = _useAutoGeneratedName
            ? GenerateAssetName(selectedType, _templateInstance)
            : _assetName.Trim();

        var safeName = SanitizeFileName(rawName);
        if (string.IsNullOrWhiteSpace(safeName))
        {
            safeName = selectedType.Name;
        }

        return $"{GetFolderPath()}/{safeName}.asset";
    }

    private void CreateModifierAsset(string folderPath)
    {
        if (!AssetDatabase.IsValidFolder(folderPath))
        {
            Debug.LogError($"Target folder does not exist: {folderPath}");
            return;
        }

        var selectedType = _modifierTypes[_selectedTypeIndex];
        var targetPath = GetTargetAssetPath();

        RefreshExistingModifiers(folderPath, targetPath);
        if (_existingModifiers.Count > 0)
        {
            Debug.LogWarning($"Modifier asset was not created. Found existing asset(s) with the same file name in selected folder/subfolders: {folderPath}");
            Selection.activeObject = _existingModifiers[0];
            EditorGUIUtility.PingObject(_existingModifiers[0]);
            return;
        }

        var asset = ScriptableObject.CreateInstance(selectedType) as Modifier;
        if (asset == null)
        {
            Debug.LogError($"Failed to create instance of {selectedType.FullName}.");
            return;
        }

        EditorUtility.CopySerialized(_templateInstance, asset);

        AssetDatabase.CreateAsset(asset, targetPath);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        EditorUtility.FocusProjectWindow();
        Selection.activeObject = asset;
        EditorGUIUtility.PingObject(asset);

        Debug.Log($"Created Modifier asset: {targetPath}", asset);
    }

    private void RefreshExistingModifiers(string folderPath, string targetAssetPath)
    {
        _existingModifiers.Clear();

        if (!AssetDatabase.IsValidFolder(folderPath))
        {
            return;
        }

        var fileName = Path.GetFileNameWithoutExtension(targetAssetPath);
        if (string.IsNullOrWhiteSpace(fileName))
        {
            return;
        }

        var guids = AssetDatabase.FindAssets("t:Modifier", new[] { folderPath });
        foreach (var guid in guids)
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            if (!string.Equals(Path.GetFileNameWithoutExtension(path), fileName, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var modifier = AssetDatabase.LoadAssetAtPath<Modifier>(path);
            if (modifier != null)
            {
                _existingModifiers.Add(modifier);
            }
        }
    }

    private string SanitizeFileName(string rawName)
    {
        var invalidChars = Path.GetInvalidFileNameChars();
        var sanitized = rawName;

        foreach (var invalidChar in invalidChars)
        {
            sanitized = sanitized.Replace(invalidChar.ToString(), string.Empty);
        }

        return sanitized;
    }

    private string GenerateAssetName(Type selectedType, Modifier source)
    {
        if (selectedType == typeof(BaseModifier) && TryGetModifierContainer(source, out var baseContainer))
        {
            return $"{baseContainer.modifierType}{baseContainer.statType}_{FormatFloatForName(baseContainer.value)}";
        }

        var baseName = selectedType.Name.Replace("Modifier", string.Empty);
        if (string.IsNullOrWhiteSpace(baseName))
        {
            baseName = selectedType.Name;
        }

        if (TryGetModifierContainer(source, out var container))
        {
            return $"{baseName}_{FormatFloatForName(container.value)}";
        }

        return baseName;
    }

    private bool TryGetModifierContainer(Modifier source, out ModifierContainer container)
    {
        container = null;
        if (source == null)
        {
            return false;
        }

        var flags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
        var field = source.GetType()
            .GetFields(flags)
            .FirstOrDefault(x => x.FieldType == typeof(ModifierContainer));

        if (field == null)
        {
            return false;
        }

        container = field.GetValue(source) as ModifierContainer;
        return container != null;
    }

    private string FormatFloatForName(float value)
    {
        return value.ToString("0.###", CultureInfo.InvariantCulture);
    }

    private IEnumerable<Type> GetLoadableTypes(Assembly assembly)
    {
        try
        {
            return assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException exception)
        {
            return exception.Types.Where(type => type != null);
        }
    }
}
